import test from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { readFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';

test('real PostgreSQL atomically persists incidents and deduplicated outbox transitions',async()=>{
  const database=`uptime_test_${randomBytes(5).toString('hex')}`;
  const adminUrl=new URL(process.env.TEST_DATABASE_URL??'postgresql://postgres@localhost:5432/postgres');
  adminUrl.pathname='/postgres';
  const admin=new pg.Client({connectionString:adminUrl.toString()});await admin.connect();
  await admin.query(`CREATE DATABASE "${database}" WITH TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C'`);
  const url=new URL(adminUrl);url.pathname=`/${database}`;
  process.env.DATABASE_URL=url.toString();
  const {pool}=await import('../src/lib/db.js');
  const {recordObservation,runDueChecks}=await import('../src/lib/monitoring.js');
  const {control}=await import('../src/lib/control.js');
  const {getPublicPage}=await import('../src/lib/public-status.js');
  const {createAdminSession,isSessionValid,revokeSession,allowLoginAttempt,credentialsMatch}=await import('../src/lib/auth.js');
  try{
    await pool.query(await readFile(new URL('../db/schema.sql',import.meta.url),'utf8'));
    await pool.query("INSERT INTO monitors(id,name,url) VALUES('fixture','Fixture','https://example.com/')");
    await pool.query('UPDATE app_settings SET alerts_enabled=true');
    const bad={ok:false,httpStatus:503,latencyMs:5,error:'HTTP 503'};
    const good={ok:true,httpStatus:200,latencyMs:4,error:null};
    const slot=(n:number)=>new Date(1700000000000+n*60000);
    const channels={discord:true,email:true};
    assert.equal(await recordObservation('fixture',slot(1),1,bad,channels),true);
    assert.equal((await pool.query('SELECT * FROM incidents')).rowCount,0);
    await Promise.all([recordObservation('fixture',slot(2),1,bad,channels),recordObservation('fixture',slot(2),1,bad,channels)]);
    assert.equal((await pool.query('SELECT * FROM checks')).rowCount,2);
    assert.equal((await pool.query('SELECT * FROM incidents')).rowCount,1);
    assert.equal((await pool.query('SELECT * FROM deliveries')).rowCount,2);
    await recordObservation('fixture',slot(3),1,bad,channels);
    assert.equal((await pool.query('SELECT * FROM deliveries')).rowCount,2);
    await recordObservation('fixture',slot(4),1,good,channels);
    assert.equal((await pool.query('SELECT resolved_at FROM incidents')).rows[0].resolved_at,null);
    await recordObservation('fixture',slot(5),1,good,channels);
    assert.ok((await pool.query('SELECT resolved_at FROM incidents')).rows[0].resolved_at);
    assert.equal((await pool.query('SELECT * FROM deliveries')).rowCount,4);
    const realAlerts=(await pool.query('SELECT payload FROM deliveries ORDER BY id')).rows.map(d=>d.payload);
    assert.equal(realAlerts[0].kind,'down');
    assert.equal(realAlerts[0].httpStatus,503);
    assert.ok(realAlerts[0].incidentId);
    assert.equal(realAlerts[0].isTest,false);
    assert.equal(realAlerts[2].kind,'recovered');
    assert.equal(realAlerts[2].httpStatus,200);
    assert.ok(realAlerts[2].durationSeconds>=0);
    await pool.query('UPDATE monitors SET version=2');
    assert.equal(await recordObservation('fixture',slot(6),1,bad,channels),false);
    assert.equal((await pool.query('SELECT * FROM checks')).rowCount,5);
    await pool.query('UPDATE monitors SET enabled=false');
    await pool.query("INSERT INTO monitors(id,name,url,next_check_at) VALUES('schedule-fixture','Schedule fixture','http://127.0.0.1/',now()-interval '0.123456 second')");
    await runDueChecks();
    assert.equal((await pool.query("SELECT * FROM checks WHERE monitor_id='schedule-fixture'")).rowCount,1,'microsecond timestamps must not prevent scheduled checks from being claimed');
    await assert.rejects(control({action:'status-page.save',title:'Status',slug:'Bad Slug',description:'',published:true,monitorIds:['fixture']}),/lowercase/);
    await control({action:'status-page.save',title:'Public fixture status',slug:'fixture-status',description:'Public health only.',published:true,monitorIds:['fixture']});
    const publicPage=await getPublicPage('fixture-status');
    assert.equal(publicPage?.title,'Public fixture status');
    assert.deepEqual(publicPage?.monitors.map(m=>Object.keys(m).sort()),[['days','id','name','status','total','passed'].sort()]);
    assert.equal(publicPage?.monitors[0].total,5);
    assert.equal(publicPage?.monitors[0].passed,2);
    assert.equal(publicPage?.monitors[0].days.length,30);
    assert.equal(publicPage?.monitors[0].days.filter(day=>day.total===0).length,29,'missing days remain empty rather than 100 percent');
    process.env.DISCORD_WEBHOOK_URL='https://discord.com/api/webhooks/123/fixture';
    const incidentCount=(await pool.query('SELECT count(*)::int AS count FROM incidents')).rows[0].count;
    const before=(await pool.query("SELECT status,failures,successes FROM monitors WHERE id='fixture'")).rows[0];
    await assert.rejects(control({action:'test',channel:'discord',monitorId:'fixture',scenario:'invented'}),/scenario/i);
    await control({action:'test',channel:'discord',monitorId:'fixture',scenario:'all'});
    const samples=(await pool.query("SELECT * FROM deliveries WHERE payload->>'isTest'='true' ORDER BY id")).rows;
    assert.equal(samples.length,8);
    assert.ok(samples.every(d=>d.incident_id===null&&d.payload.monitorName==='Fixture'));
    assert.equal((await pool.query('SELECT count(*)::int AS count FROM incidents')).rows[0].count,incidentCount);
    assert.deepEqual((await pool.query("SELECT status,failures,successes FROM monitors WHERE id='fixture'")).rows[0],before);
    await assert.rejects(control({action:'test',channel:'discord',monitorId:'fixture',scenario:'recovered'}),/last minute/);
    await control({action:'alerts',enabled:false});
    assert.equal((await pool.query("SELECT count(*)::int AS count FROM deliveries WHERE payload->>'isTest'='true' AND status='pending'")).rows[0].count,8,'pausing real alerts must preserve requested tests');
    process.env.NOTIFICATION_ENCRYPTION_KEY='ab'.repeat(32);
    const {getNotificationSettings,notificationSettingsView,notificationReadiness}=await import('../src/lib/notification-settings.js');
    const {getDashboard}=await import('../src/lib/dashboard.js');
    const monitorStateBefore=(await pool.query('SELECT id,status,failures,successes,version,next_check_at FROM monitors ORDER BY id')).rows;
    await control({action:'monitors.reorder',monitorIds:['schedule-fixture','fixture']});
    assert.deepEqual((await getDashboard()).monitors.map(m=>m.id),['schedule-fixture','fixture']);
    const {buildOverview}=await import('../src/lib/overview-content.js');
    const ordered=await getDashboard();
    assert.ok(buildOverview(ordered.monitors,ordered.now,'').embeds[0].fields[0].name.includes('Schedule fixture'));
    await assert.rejects(control({action:'monitors.reorder',monitorIds:['fixture','fixture']}),/once/i);
    await assert.rejects(control({action:'monitors.reorder',monitorIds:['fixture']}),/changed/i);
    await assert.rejects(control({action:'monitors.reorder',monitorIds:['fixture','missing']}),/changed/i);
    await pool.query(await readFile(new URL('../db/migrations/003-monitor-order.sql',import.meta.url),'utf8'));
    assert.deepEqual((await getDashboard()).monitors.map(m=>m.id),['schedule-fixture','fixture'],'reapplying migration preserves saved order');
    assert.deepEqual((await pool.query('SELECT id,status,failures,successes,version,next_check_at FROM monitors ORDER BY id')).rows,monitorStateBefore,'reordering does not change monitoring state');
    await control({action:'status-page.save',title:'Ordered status',slug:'ordered-status',published:true,monitorIds:['fixture','schedule-fixture']});
    assert.deepEqual((await getPublicPage('ordered-status'))?.monitors.map(m=>m.id),['schedule-fixture','fixture'],'public pages follow monitor order instead of selection order');
    await control({action:'monitors.reorder',monitorIds:['fixture','schedule-fixture']});
    assert.deepEqual((await getPublicPage('ordered-status'))?.monitors.map(m=>m.id),['fixture','schedule-fixture'],'later ordering changes apply without resaving the public page');
    assert.deepEqual((await getPublicPage('fixture-status'))?.monitors.map(m=>m.id),['fixture'],'only selected monitors remain public');
    await control({action:'monitors.reorder',monitorIds:['schedule-fixture','fixture']});
    const createInput={action:'monitors.create',name:' New service ',project:' Example ',url:' https://example.org#status '};
    for(const invalid of [{name:''},{project:''},{url:''},{url:'http://127.0.0.1'},{url:'https://user:pass@example.org'},{url:'https://example.org:8080'}]){
      await assert.rejects(control({...createInput,...invalid}));
    }
    const creates=await Promise.allSettled([control(createInput),control(createInput)]);
    assert.equal(creates.filter(result=>result.status==='fulfilled').length,1,'concurrent submissions create one monitor');
    const created=(await pool.query("SELECT *,next_check_at<=now() AS due FROM monitors WHERE url='https://example.org/'")).rows[0];
    assert.equal(created.name,'New service');assert.equal(created.project,'Example');
    assert.equal(created.enabled,true);assert.equal(created.status,'unknown');assert.equal(created.interval_seconds,60);assert.equal(created.due,true);
    assert.equal(created.last_checked_at,null);
    const withCreated=await getDashboard();
    assert.deepEqual(withCreated.monitors.map(m=>m.id),['schedule-fixture','fixture',created.id],'new monitors append to saved order');
    assert.ok(buildOverview(withCreated.monitors,withCreated.now,'').embeds[0].fields.at(-1)?.name.includes('New service'));
    assert.deepEqual((await getPublicPage('fixture-status'))?.monitors.map(m=>m.id),['fixture'],'creation does not expose a monitor publicly');
    assert.deepEqual((await pool.query('SELECT id,status,failures,successes,version,next_check_at FROM monitors WHERE id<>$1 ORDER BY id',[created.id])).rows,monitorStateBefore);
    await assert.rejects(control({...createInput,url:'https://example.org/'}),/already/i);
    await pool.query('DELETE FROM monitors WHERE id=$1',[created.id]);
    const replacementWebhook='https://discord.com/api/webhooks/456/replacement_fixture_secret';
    await assert.rejects(control({action:'notifications.save',channel:'discord',enabled:true,webhook:'https://example.com/webhook'}),/Discord webhook/);
    await control({action:'notifications.save',channel:'discord',enabled:true,webhook:replacementWebhook});
    await control({action:'notifications.save',channel:'discord',enabled:true,webhook:''});
    assert.equal((await getNotificationSettings()).discord.webhook,replacementWebhook,'blank webhook retains the saved value');
    const emailInput={action:'notifications.save',channel:'email',enabled:true,host:'smtp.example.com',port:587,user:'sender@example.com',password:'fixture-smtp-secret',from:'Uptime <sender@example.com>',to:'owner@example.com'};
    await assert.rejects(control({...emailInput,host:'127.0.0.1'}),/SMTP hostname/);
    await assert.rejects(control({...emailInput,to:'not-an-email'}),/email addresses/);
    await control(emailInput);
    await control({...emailInput,password:'',to:'second@example.com',port:465});
    const savedSettings=await getNotificationSettings();
    assert.equal(savedSettings.email.password,'fixture-smtp-secret','blank password retains the saved secret');
    assert.deepEqual(savedSettings.email.to,['second@example.com'],'configuration is read fresh after save');
    assert.equal(savedSettings.email.secure,true,'port 465 uses implicit TLS');
    const ciphertext=JSON.stringify((await pool.query('SELECT * FROM notification_settings')).rows);
    assert.equal(ciphertext.includes('fixture-smtp-secret'),false);
    assert.equal(ciphertext.includes(replacementWebhook),false);
    for(const visible of [notificationSettingsView(savedSettings),(await getDashboard()).config]){
      const json=JSON.stringify(visible);
      assert.equal(json.includes('fixture-smtp-secret'),false);
      assert.equal(json.includes(replacementWebhook),false);
    }
    process.env.NOTIFICATION_ENCRYPTION_KEY='cd'.repeat(32);
    await assert.rejects(getNotificationSettings(),'wrong encryption keys must fail closed');
    process.env.NOTIFICATION_ENCRYPTION_KEY='ab'.repeat(32);
    await control({action:'notifications.save',channel:'discord',enabled:false,webhook:''});
    assert.equal(notificationReadiness(await getNotificationSettings()).discord,false,'disabled settings override environment fallback');
    assert.equal((await pool.query("SELECT count(*)::int AS count FROM deliveries WHERE channel='discord' AND status='pending'")).rows[0].count,0);
    await assert.rejects(control({action:'test',channel:'discord',monitorId:'fixture'}),/enable Discord/);
    const {refreshOverview,OverviewError}=await import('../src/lib/discord-overview.js');
    const overviewCalls:(string|null)[]=[];
    const write=async(webhook:string,id:string|null)=>{assert.equal(webhook,replacementWebhook);overviewCalls.push(id);return id??'10000000001';};
    await refreshOverview(write);
    assert.deepEqual(overviewCalls,[null],'default overview uses incident webhook even when incident alerts are disabled');
    assert.equal((await pool.query('SELECT message_id FROM overview_message')).rows[0].message_id,'10000000001');
    await pool.query('UPDATE overview_message SET next_attempt_at=now()');
    await Promise.all([refreshOverview(write),refreshOverview(write)]);
    assert.deepEqual(overviewCalls,[null,'10000000001'],'concurrent refreshes reuse one saved message');
    await pool.query('UPDATE overview_message SET next_attempt_at=now()');
    await refreshOverview(async(webhook,id)=>{if(id)throw new OverviewError('Deleted',0,true);return write(webhook,id);});
    assert.deepEqual(overviewCalls,[null,'10000000001',null],'a confirmed deleted message is recreated');
    await pool.query('UPDATE overview_message SET next_attempt_at=now()');
    await refreshOverview(async()=>{throw new OverviewError('Rate limit',120000);});
    assert.ok((await pool.query("SELECT next_attempt_at>now()+interval '115 seconds' AS delayed FROM overview_message")).rows[0].delayed);
    await pool.query('UPDATE overview_message SET message_id=NULL,next_attempt_at=now()');
    await refreshOverview(async()=>{throw new OverviewError('Creation unconfirmed',60000,false,true);});
    assert.equal((await pool.query('SELECT creation_pending FROM overview_message')).rows[0].creation_pending,true);
    await pool.query('UPDATE overview_message SET next_attempt_at=now()');
    await refreshOverview(async()=>{assert.fail('an ambiguous create must not automatically create a duplicate');});
    await control({action:'overview.recover',messageId:'10000000002'});
    await refreshOverview(write);
    assert.equal(overviewCalls.at(-1),'10000000002','adopting a confirmed message resumes editing');
    const overviewWebhook='https://discord.com/api/webhooks/789/overview_fixture_secret';
    await control({action:'notifications.save',channel:'overview',enabled:true,useIncidentWebhook:false,webhook:overviewWebhook});
    assert.equal(JSON.stringify(notificationSettingsView(await getNotificationSettings())).includes(overviewWebhook),false);
    await refreshOverview(async(webhook,id)=>{assert.equal(webhook,overviewWebhook);assert.equal(id,null,'a new destination gets its own message');return '10000000003';});
    await control({action:'notifications.save',channel:'overview',enabled:true,useIncidentWebhook:true});
    assert.equal((await getNotificationSettings()).overview.webhook,'','returning to the incident webhook removes the override');
    await refreshOverview(write);
    await control({action:'notifications.save',channel:'overview',enabled:false,useIncidentWebhook:true});
    await refreshOverview(async()=>{assert.fail('disabled overviews must not post');});
    assert.equal(JSON.stringify(publicPage).includes('example.com'),false,'public data must not expose monitor target URLs');
    await control({action:'status-page.save',id:publicPage?.id,title:'Public fixture status',slug:'fixture-status',description:'Public health only.',published:false,monitorIds:['fixture']});
    assert.equal(await getPublicPage('fixture-status'),null,'unpublished pages are inaccessible');
    process.env.ADMIN_USERNAME='owner@example.com';
    process.env.ADMIN_PASSWORD='fixture-password';
    process.env.SESSION_SECRET='isolated-session-secret-for-tests-only';
    assert.equal(credentialsMatch('OWNER@example.com','fixture-password'),true);
    assert.equal(credentialsMatch('owner@example.com','wrong'),false);
    assert.equal(credentialsMatch(null,null),false);
    const session=await createAdminSession();
    assert.equal(await isSessionValid(session),true);
    assert.equal(await isSessionValid('forged-session'),false);
    await revokeSession(session);
    assert.equal(await isSessionValid(session),false,'logout revokes the server session');
    const expired=await createAdminSession();
    await pool.query("UPDATE admin_sessions SET expires_at=now()-interval '1 second'");
    assert.equal(await isSessionValid(expired),false,'expired sessions cannot access private data');
    const changedPasswordSession=await createAdminSession();
    process.env.ADMIN_PASSWORD='changed-fixture-password';
    assert.equal(await isSessionValid(changedPasswordSession),false,'password changes invalidate previous sessions');
    const attempts=await Promise.all(Array.from({length:12},()=>allowLoginAttempt()));
    assert.equal(attempts.filter(Boolean).length,10,'login throttling is atomic across concurrent requests');
  }finally{
    await pool.end();
    await admin.query(`DROP DATABASE "${database}"`);await admin.end();
  }
});
