import test from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import { readFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';

test('real PostgreSQL atomically persists incidents and deduplicated outbox transitions',async()=>{
  const database=`uptime_test_${randomBytes(5).toString('hex')}`;
  const adminUrl=new URL(process.env.TEST_DATABASE_URL??'postgresql://postgres@localhost:5432/postgres');
  adminUrl.pathname='/postgres';
  const admin=new pg.Client({connectionString:adminUrl.toString()});await admin.connect();
  await admin.query(`CREATE DATABASE "${database}" WITH TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C'`);
  const url=new URL(adminUrl);url.pathname=`/${database}`;
  process.env.DATABASE_URL=url.toString();
  const {pool}=await import('../src/lib/db.js');
  const {recordObservation,runDueChecks}=await import('../src/lib/monitoring.js');
  const {control}=await import('../src/lib/control.js');
  const {getPublicPage}=await import('../src/lib/public-status.js');
  const {createAdminSession,isSessionValid,revokeSession,allowLoginAttempt,credentialsMatch}=await import('../src/lib/auth.js');
  try{
    await pool.query(await readFile(new URL('../db/schema.sql',import.meta.url),'utf8'));
    await pool.query("INSERT INTO monitors(id,name,url) VALUES('fixture','Fixture','https://example.com/')");
    await pool.query('UPDATE app_settings SET alerts_enabled=true');
    const bad={ok:false,httpStatus:503,latencyMs:5,error:'HTTP 503'};
    const good={ok:true,httpStatus:200,latencyMs:4,error:null};
    const slot=(n:number)=>new Date(1700000000000+n*60000);
    const channels={discord:true,email:true};
    assert.equal(await recordObservation('fixture',slot(1),1,bad,channels),true);
    assert.equal((await pool.query('SELECT * FROM incidents')).rowCount,0);
    await Promise.all([recordObservation('fixture',slot(2),1,bad,channels),recordObservation('fixture',slot(2),1,bad,channels)]);
    assert.equal((await pool.query('SELECT * FROM checks')).rowCount,2);
    assert.equal((await pool.query('SELECT * FROM incidents')).rowCount,1);
    assert.equal((await pool.query('SELECT * FROM deliveries')).rowCount,2);
    await recordObservation('fixture',slot(3),1,bad,channels);
    assert.equal((await pool.query('SELECT * FROM deliveries')).rowCount,2);
    await recordObservation('fixture',slot(4),1,good,channels);
    assert.equal((await pool.query('SELECT resolved_at FROM incidents')).rows[0].resolved_at,null);
    await recordObservation('fixture',slot(5),1,good,channels);
    assert.ok((await pool.query('SELECT resolved_at FROM incidents')).rows[0].resolved_at);
    assert.equal((await pool.query('SELECT * FROM deliveries')).rowCount,4);
    const realAlerts=(await pool.query('SELECT payload FROM deliveries ORDER BY id')).rows.map(d=>d.payload);
    assert.equal(realAlerts[0].kind,'down');
    assert.equal(realAlerts[0].httpStatus,503);
    assert.ok(realAlerts[0].incidentId);
    assert.equal(realAlerts[0].isTest,false);
    assert.equal(realAlerts[2].kind,'recovered');
    assert.equal(realAlerts[2].httpStatus,200);
    assert.ok(realAlerts[2].durationSeconds>=0);
    await pool.query('UPDATE monitors SET version=2');
    assert.equal(await recordObservation('fixture',slot(6),1,bad,channels),false);
    assert.equal((await pool.query('SELECT * FROM checks')).rowCount,5);
    await pool.query('UPDATE monitors SET enabled=false');
    await pool.query("INSERT INTO monitors(id,name,url,next_check_at) VALUES('schedule-fixture','Schedule fixture','http://127.0.0.1/',now()-interval '0.123456 second')");
    await runDueChecks();
    assert.equal((await pool.query("SELECT * FROM checks WHERE monitor_id='schedule-fixture'")).rowCount,1,'microsecond timestamps must not prevent scheduled checks from being claimed');
    await assert.rejects(control({action:'status-page.save',title:'Status',slug:'Bad Slug',description:'',published:true,monitorIds:['fixture']}),/lowercase/);
    await control({action:'status-page.save',title:'Public fixture status',slug:'fixture-status',description:'Public health only.',published:true,monitorIds:['fixture']});
    const publicPage=await getPublicPage('fixture-status');
    assert.equal(publicPage?.title,'Public fixture status');
    assert.deepEqual(publicPage?.monitors.map(m=>Object.keys(m).sort()),[['days','id','name','status','total','passed'].sort()]);
    assert.equal(publicPage?.monitors[0].total,5);
    assert.equal(publicPage?.monitors[0].passed,2);
    assert.equal(publicPage?.monitors[0].days.length,30);
    assert.equal(publicPage?.monitors[0].days.filter(day=>day.total===0).length,29,'missing days remain empty rather than 100 percent');
    process.env.DISCORD_WEBHOOK_URL='https://discord.com/api/webhooks/123/fixture';
    const incidentCount=(await pool.query('SELECT count(*)::int AS count FROM incidents')).rows[0].count;
    const before=(await pool.query("SELECT status,failures,successes FROM monitors WHERE id='fixture'")).rows[0];
    await assert.rejects(control({action:'test',channel:'discord',monitorId:'fixture',scenario:'invented'}),/scenario/i);
    await control({action:'test',channel:'discord',monitorId:'fixture',scenario:'all'});
    const samples=(await pool.query("SELECT * FROM deliveries WHERE payload->>'isTest'='true' ORDER BY id")).rows;
    assert.equal(samples.length,8);
    assert.ok(samples.every(d=>d.incident_id===null&&d.payload.monitorName==='Fixture'));
    assert.equal((await pool.query('SELECT count(*)::int AS count FROM incidents')).rows[0].count,incidentCount);
    assert.deepEqual((await pool.query("SELECT status,failures,successes FROM monitors WHERE id='fixture'")).rows[0],before);
    await assert.rejects(control({action:'test',channel:'discord',monitorId:'fixture',scenario:'recovered'}),/last minute/);
    await control({action:'alerts',enabled:false});
    assert.equal((await pool.query("SELECT count(*)::int AS count FROM deliveries WHERE payload->>'isTest'='true' AND status='pending'")).rows[0].count,8,'pausing real alerts must preserve requested tests');
    process.env.NOTIFICATION_ENCRYPTION_KEY='ab'.repeat(32);
    const {getNotificationSettings,notificationSettingsView,notificationReadiness}=await import('../src/lib/notification-settings.js');
    const {getDashboard}=await import('../src/lib/dashboard.js');
    const replacementWebhook='https://discord.com/api/webhooks/456/replacement_fixture_secret';
    await assert.rejects(control({action:'notifications.save',channel:'discord',enabled:true,webhook:'https://example.com/webhook'}),/Discord webhook/);
    await control({action:'notifications.save',channel:'discord',enabled:true,webhook:replacementWebhook});
    await control({action:'notifications.save',channel:'discord',enabled:true,webhook:''});
    assert.equal((await getNotificationSettings()).discord.webhook,replacementWebhook,'blank webhook retains the saved value');
    const emailInput={action:'notifications.save',channel:'email',enabled:true,host:'smtp.example.com',port:587,user:'sender@example.com',password:'fixture-smtp-secret',from:'Uptime <sender@example.com>',to:'owner@example.com'};
    await assert.rejects(control({...emailInput,host:'127.0.0.1'}),/SMTP hostname/);
    await assert.rejects(control({...emailInput,to:'not-an-email'}),/email addresses/);
    await control(emailInput);
    await control({...emailInput,password:'',to:'second@example.com',port:465});
    const savedSettings=await getNotificationSettings();
    assert.equal(savedSettings.email.password,'fixture-smtp-secret','blank password retains the saved secret');
    assert.deepEqual(savedSettings.email.to,['second@example.com'],'configuration is read fresh after save');
    assert.equal(savedSettings.email.secure,true,'port 465 uses implicit TLS');
    const ciphertext=JSON.stringify((await pool.query('SELECT * FROM notification_settings')).rows);
    assert.equal(ciphertext.includes('fixture-smtp-secret'),false);
    assert.equal(ciphertext.includes(replacementWebhook),false);
    for(const visible of [notificationSettingsView(savedSettings),(await getDashboard()).config]){
      const json=JSON.stringify(visible);
      assert.equal(json.includes('fixture-smtp-secret'),false);
      assert.equal(json.includes(replacementWebhook),false);
    }
    process.env.NOTIFICATION_ENCRYPTION_KEY='cd'.repeat(32);
    await assert.rejects(getNotificationSettings(),'wrong encryption keys must fail closed');
    process.env.NOTIFICATION_ENCRYPTION_KEY='ab'.repeat(32);
    await control({action:'notifications.save',channel:'discord',enabled:false,webhook:''});
    assert.equal(notificationReadiness(await getNotificationSettings()).discord,false,'disabled settings override environment fallback');
    assert.equal((await pool.query("SELECT count(*)::int AS count FROM deliveries WHERE channel='discord' AND status='pending'")).rows[0].count,0);
    await assert.rejects(control({action:'test',channel:'discord',monitorId:'fixture'}),/enable Discord/);
    assert.equal(JSON.stringify(publicPage).includes('example.com'),false,'public data must not expose monitor target URLs');
    await control({action:'status-page.save',id:publicPage?.id,title:'Public fixture status',slug:'fixture-status',description:'Public health only.',published:false,monitorIds:['fixture']});
    assert.equal(await getPublicPage('fixture-status'),null,'unpublished pages are inaccessible');
    process.env.ADMIN_USERNAME='owner@example.com';
    process.env.ADMIN_PASSWORD='fixture-password';
    process.env.SESSION_SECRET='isolated-session-secret-for-tests-only';
    assert.equal(credentialsMatch('OWNER@example.com','fixture-password'),true);
    assert.equal(credentialsMatch('owner@example.com','wrong'),false);
    assert.equal(credentialsMatch(null,null),false);
    const session=await createAdminSession();
    assert.equal(await isSessionValid(session),true);
    assert.equal(await isSessionValid('forged-session'),false);
    await revokeSession(session);
    assert.equal(await isSessionValid(session),false,'logout revokes the server session');
    const expired=await createAdminSession();
    await pool.query("UPDATE admin_sessions SET expires_at=now()-interval '1 second'");
    assert.equal(await isSessionValid(expired),false,'expired sessions cannot access private data');
    const changedPasswordSession=await createAdminSession();
    process.env.ADMIN_PASSWORD='changed-fixture-password';
    assert.equal(await isSessionValid(changedPasswordSession),false,'password changes invalidate previous sessions');
    const attempts=await Promise.all(Array.from({length:12},()=>allowLoginAttempt()));
    assert.equal(attempts.filter(Boolean).length,10,'login throttling is atomic across concurrent requests');
  }finally{
    await pool.end();
    await admin.query(`DROP DATABASE "${database}"`);await admin.end();
  }
});
